USE [POSEZ2U_V1]
GO

ALTER TABLE [dbo].[SHIFT_HISTORY] DROP CONSTRAINT [DF_SHIFT_HISTORY_UpdateDate]
GO

ALTER TABLE [dbo].[SHIFT_HISTORY] DROP CONSTRAINT [DF_SHIFT_HISTORY_UpdateBy]
GO

ALTER TABLE [dbo].[SHIFT_HISTORY] DROP CONSTRAINT [DF_SHIFT_HISTORY_CreateDate]
GO

ALTER TABLE [dbo].[SHIFT_HISTORY] DROP CONSTRAINT [DF_SHIFT_HISTORY_CreateBy]
GO

ALTER TABLE [dbo].[SHIFT_HISTORY] DROP CONSTRAINT [DF_SHIFT_HISTORY_SafeDrop]
GO

ALTER TABLE [dbo].[SHIFT_HISTORY] DROP CONSTRAINT [DF_SHIFT_HISTORY_CashEnd]
GO

ALTER TABLE [dbo].[SHIFT_HISTORY] DROP CONSTRAINT [DF_SHIFT_HISTORY_CashStart]
GO

ALTER TABLE [dbo].[SHIFT_HISTORY] DROP CONSTRAINT [DF_SHIFT_HISTORY_Status]
GO

ALTER TABLE [dbo].[SHIFT_HISTORY] DROP CONSTRAINT [DF_SHIFT_HISTORY_StartShift]
GO

/****** Object:  Table [dbo].[SHIFT_HISTORY]    Script Date: 1/3/2016 10:58:22 PM ******/
DROP TABLE [dbo].[SHIFT_HISTORY]
GO

/****** Object:  Table [dbo].[SHIFT_HISTORY]    Script Date: 1/3/2016 10:58:22 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SHIFT_HISTORY](
	[ShiftHistoryID] [INT] IDENTITY(1,1) NOT NULL,
	[StaffID] [INT] NULL,
	[ShiftName] [NVARCHAR](500) NULL,
	[StartShift] [DATETIME] NULL,
	[EndShift] [DATETIME] NULL,
	[Status] [INT] NULL,
	[CashStart] [FLOAT] NULL,
	[CashEnd] [FLOAT] NULL,
	[SafeDrop] [FLOAT] NULL,
	[Note] [NVARCHAR](MAX) NULL,
	[CreateBy] [INT] NULL,
	[CreateDate] [DATETIME] NULL,
	[UpdateBy] [INT] NULL,
	[UpdateDate] [DATETIME] NULL,
 CONSTRAINT [PK_SHIFT_HISTORY_1] PRIMARY KEY CLUSTERED 
(
	[ShiftHistoryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[SHIFT_HISTORY] ADD  CONSTRAINT [DF_SHIFT_HISTORY_StartShift]  DEFAULT (GETDATE()) FOR [StartShift]
GO

ALTER TABLE [dbo].[SHIFT_HISTORY] ADD  CONSTRAINT [DF_SHIFT_HISTORY_Status]  DEFAULT ((0)) FOR [Status]
GO

ALTER TABLE [dbo].[SHIFT_HISTORY] ADD  CONSTRAINT [DF_SHIFT_HISTORY_CashStart]  DEFAULT ((0)) FOR [CashStart]
GO

ALTER TABLE [dbo].[SHIFT_HISTORY] ADD  CONSTRAINT [DF_SHIFT_HISTORY_CashEnd]  DEFAULT ((0)) FOR [CashEnd]
GO

ALTER TABLE [dbo].[SHIFT_HISTORY] ADD  CONSTRAINT [DF_SHIFT_HISTORY_SafeDrop]  DEFAULT ((0)) FOR [SafeDrop]
GO

ALTER TABLE [dbo].[SHIFT_HISTORY] ADD  CONSTRAINT [DF_SHIFT_HISTORY_CreateBy]  DEFAULT ((0)) FOR [CreateBy]
GO

ALTER TABLE [dbo].[SHIFT_HISTORY] ADD  CONSTRAINT [DF_SHIFT_HISTORY_CreateDate]  DEFAULT (GETDATE()) FOR [CreateDate]
GO

ALTER TABLE [dbo].[SHIFT_HISTORY] ADD  CONSTRAINT [DF_SHIFT_HISTORY_UpdateBy]  DEFAULT ((0)) FOR [UpdateBy]
GO

ALTER TABLE [dbo].[SHIFT_HISTORY] ADD  CONSTRAINT [DF_SHIFT_HISTORY_UpdateDate]  DEFAULT (GETDATE()) FOR [UpdateDate]
GO


