//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelPOS.ModelEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POSEZ2UEntities : DbContext
    {
        public POSEZ2UEntities()
            : base("name=POSEZ2UEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATALOGUE> CATALOGUEs { get; set; }
        public virtual DbSet<CATEGORY> CATEGORies { get; set; }
        public virtual DbSet<CLIENT> CLIENTs { get; set; }
        public virtual DbSet<DEPARMENT> DEPARMENTs { get; set; }
        public virtual DbSet<FLOOR> FLOORs { get; set; }
        public virtual DbSet<MAP_CATEGORY_TO_CATALOGUE> MAP_CATEGORY_TO_CATALOGUE { get; set; }
        public virtual DbSet<MAP_MODIFIRE_TO_PRODUCT> MAP_MODIFIRE_TO_PRODUCT { get; set; }
        public virtual DbSet<MAP_PRODUCT_TO_CATEGORY> MAP_PRODUCT_TO_CATEGORY { get; set; }
        public virtual DbSet<MENU> MENUs { get; set; }
        public virtual DbSet<MODIFIRE> MODIFIREs { get; set; }
        public virtual DbSet<MODIFIRE_PRICE> MODIFIRE_PRICE { get; set; }
        public virtual DbSet<PAYMENT_TYPE> PAYMENT_TYPE { get; set; }
        public virtual DbSet<PERMISSION> PERMISSIONs { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTs { get; set; }
        public virtual DbSet<PRODUCT_PRICE> PRODUCT_PRICE { get; set; }
        public virtual DbSet<SHIFT_HISTORY> SHIFT_HISTORY { get; set; }
        public virtual DbSet<STAFF> STAFFs { get; set; }
        public virtual DbSet<SUB_MENU> SUB_MENU { get; set; }
        public virtual DbSet<INVOICE> INVOICEs { get; set; }
        public virtual DbSet<INVOICE_DETAIL> INVOICE_DETAIL { get; set; }
        public virtual DbSet<INVOICE_DETAIL_MODIFIRE> INVOICE_DETAIL_MODIFIRE { get; set; }
        public virtual DbSet<ORDER> ORDERs { get; set; }
        public virtual DbSet<ORDER_DATE> ORDER_DATE { get; set; }
        public virtual DbSet<ORDER_DETAIL> ORDER_DETAIL { get; set; }
        public virtual DbSet<ORDER_DETAIL_DATE> ORDER_DETAIL_DATE { get; set; }
        public virtual DbSet<ORDER_DETAIL_MODIFIRE> ORDER_DETAIL_MODIFIRE { get; set; }
        public virtual DbSet<ORDER_DETAIL_MODIFIRE_DATE> ORDER_DETAIL_MODIFIRE_DATE { get; set; }
        public virtual DbSet<PAYMENT_INVOICE_HISTORY> PAYMENT_INVOICE_HISTORY { get; set; }
    }
}
